# Single-file docker compose example (no .env).
#
# IMPORTANT: Change the password/token before exposing to the Internet.
services:
  panel:
    image: ign1x/elegantmc-panel:latest
    environment:
      ELEGANTMC_PANEL_HOST: "0.0.0.0"
      ELEGANTMC_PANEL_PORT: "3000"
      ELEGANTMC_PANEL_ADMIN_PASSWORD: "change-me"
      ELEGANTMC_PANEL_SECURE_COOKIE: ""
      ELEGANTMC_PANEL_HSTS: ""
      ELEGANTMC_ENABLE_ADVANCED: ""
      ELEGANTMC_DAEMON_TOKENS_JSON: "{\"local-node\":\"local-dev-token\"}"
      ELEGANTMC_PANEL_DATA_DIR: "/data"
    ports:
      - "3000:3000"
    volumes:
      - elegantmc-panel-data:/data
    restart: unless-stopped

  daemon:
    image: ign1x/elegantmc-daemon:latest
    environment:
      ELEGANTMC_PANEL_WS_URL: "ws://panel:3000/ws/daemon"
      ELEGANTMC_TOKEN: "local-dev-token"
      ELEGANTMC_DAEMON_ID: "local-node"
      ELEGANTMC_BASE_DIR: "/data"
    ports:
      - "25565-25600:25565-25600"
    volumes:
      - elegantmc-data:/data
    depends_on:
      - panel
    restart: unless-stopped

volumes:
  elegantmc-data: {}
  elegantmc-panel-data: {}

