// Generated by `cargo run -p alloy-control --bin export_rspc_bindings`.

// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type DirEntryDto = { name: string; is_dir: boolean; size_bytes: number }

export type ProceduresLegacy = { queries: { key: "agent.health"; input: null; result: { status: string; agent_version: string } } | { key: "control.ping"; input: null; result: { status: string; version: string } } | { key: "fs.listDir"; input: { path: string | null }; result: { entries: DirEntryDto[] } } | { key: "fs.readFile"; input: { path: string; offset: number | null; limit: number | null }; result: { text: string; size_bytes: number } } | { key: "process.list"; input: null; result: ({ process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null })[] } | { key: "process.logsTail"; input: { process_id: string; cursor: string | null; limit: number | null }; result: { lines: string[]; next_cursor: string } } | { key: "process.status"; input: { process_id: string }; result: { process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null } } | { key: "process.templates"; input: null; result: { template_id: string; display_name: string }[] }; mutations: { key: "process.start"; input: { template_id: string; params: Partial<{ [key in string]: string }> }; result: { process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null } } | { key: "process.stop"; input: { process_id: string; timeout_ms: number | null }; result: { process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null } }; subscriptions: never }

export type Procedures = {
	agent: {
	health: { kind: "query", input: null, output: { status: string; agent_version: string }, error: unknown },
},
	control: {
	ping: { kind: "query", input: null, output: { status: string; version: string }, error: unknown },
},
	fs: {
	listDir: { kind: "query", input: { path: string | null }, output: { entries: DirEntryDto[] }, error: unknown },
	readFile: { kind: "query", input: { path: string; offset: number | null; limit: number | null }, output: { text: string; size_bytes: number }, error: unknown },
},
	process: {
	list: { kind: "query", input: null, output: ({ process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null })[], error: unknown },
	logsTail: { kind: "query", input: { process_id: string; cursor: string | null; limit: number | null }, output: { lines: string[]; next_cursor: string }, error: unknown },
	start: { kind: "mutation", input: { template_id: string; params: Partial<{ [key in string]: string }> }, output: { process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null }, error: unknown },
	status: { kind: "query", input: { process_id: string }, output: { process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null }, error: unknown },
	stop: { kind: "mutation", input: { process_id: string; timeout_ms: number | null }, output: { process_id: string; template_id: string; state: string; pid: number | null; exit_code: number | null; message: string | null }, error: unknown },
	templates: { kind: "query", input: null, output: { template_id: string; display_name: string }[], error: unknown },
},
}